routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::get('lc-admin', 'Laracode\AdminController@index')->name('lc-admin');
Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel'], 'namespace' => 'Laracode'], function () {

    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    // Route::resource('roles', 'RoleController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('roles', 'RoleController', ['except' => ['show', 'edit']]);
    // Route::resource('permissions', 'PermissionController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('permissions', 'PermissionController', ['except' => ['show', 'edit']]);
    Route::resource('users', 'UserController');

    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::post('languages/{name}', 'LanguageController@store')->name('store-language');
    Route::get('set-language/{language}', 'LanguageController@update')->name('set-language');

    Route::put('users', 'UserController@updateMany'); // obrisati?
    Route::get('activity-log', 'AdminController@activityLog')->name('activity-log');

    Route::post('newsletter', 'NewsletterController@store')->name('store-newsletter');
});

app/Http/Controllers/Laracode/PermissionController.php
<?php

namespace App\Http\Controllers\Laracode;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax())
            return DataTables::eloquent(
                Permission::query()->with('roles'))
                    ->addColumn('action', function ($permission) {
                           return view('lc-admin.permissions.datatable-action', compact('permission'));
                       })
                    ->make(true);

        return view('lc-admin.permissions.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $permission = Permission::create(['name' => $request->name]);

        $permission->syncRoles($request->roles);

        return 201;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::find($id);

        $permission->update(['name' => $request->name]);
        $permission->syncRoles($request->roles);

        return 200;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Permission::destroy($id);

        return 200;
    }

}

resources/views/lc-admin/permissions/index.blade.php
@extends('lc-admin.layouts.master')
@section('title', __('Permissions'))

@section('external-css')
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/datatables-net/media/css/dataTables.bootstrap4.min.css') }}"> <!-- original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/datatables-net/datatables.min.css') }}"> <!-- customization -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/select2/css/select2.min.css') }}"> <!-- Original -->
<link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/libs/select2/select2.min.css') }}"> <!-- Customization -->
@endsection
@section('content')
<div class="ks-column ks-page">
    <div class="ks-page-header">
        <section class="ks-title">
            <h3>{{ __('Permissions') }}</h3>
            
            <div class="ks-controls">
                {{ Breadcrumbs::render('lc-admin.permissions') }}


                <button class="btn btn-outline-primary ks-light ks-content-nav-toggle" data-block-toggle=".ks-content-nav > .ks-nav">Menu</button>
            </div>
        </section>
    </div>
    <div class="ks-page-content">
        <div class="ks-page-content-body ks-invoices ks-body-wrap">
            <div class="ks-body-wrap-container">
                <div class="ks-full-table">
                    <div class="ks-full-table-header">
                        <h4 class="ks-full-table-name">{{ __('All permissions')}}</h4>
                        <div class="ks-controls">
                            <a href="{{ route('lc-admin.permissions.create') }}">
                                <button class="btn btn-primary">{{ __('New role')}}</button>
                            </a>
                        </div>
                    </div>
                    <table id="permissions-table" class="table ks-table-info dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>{{ __('ID') }}</th>
                                <th>{{ __('Name') }}</th>
                                <th>{{ __('Roles that have this permission') }}</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('external-js')
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/datatables-net/media/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/select2/js/select2.min.js') }}"></script>
<script type="application/javascript">
var DatatablesDataSourceAjaxServer = {
    init: function () {
        $("#permissions-table").DataTable({
            responsive: true, 
            searchDelay: 500, 
            processing: true, 
            serverSide: true, 
            ajax:"/lc-admin/permissions", 
            columns: [
                { data: "id" },
                { data: "name" },
                { 
                data: "roles", 
                    searchable: false,
                    orderable: false
                },
                { data: "action" }
            ],
            columnDefs: [
                {
                    targets: 2,
                    render: function (data) {
                        roles = [];
                        $.each(data, function (i, role) {
                            roles.push(role.name);
                        });

                        return roles.join(', ');
                    }
                }
            ],
            "initComplete": function () {
                $('.dataTables_wrapper select').select2({
                    minimumResultsForSearch: Infinity
                });
            }
        })
    }
};

jQuery(document).ready(function () {
    DatatablesDataSourceAjaxServer.init();
});

</script>
@endsection