routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::get('lc-admin', 'Laracode\AdminController@index')->name('lc-admin');
Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel'], 'namespace' => 'Laracode'], function () {

    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    // Route::resource('roles', 'RoleController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('roles', 'RoleController', ['except' => ['show', 'edit']]);
    // Route::resource('permissions', 'PermissionController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('permissions', 'PermissionController', ['except' => ['show', 'edit']]);
    Route::resource('users', 'UserController');

    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::post('languages/{name}', 'LanguageController@store')->name('store-language');
    Route::get('set-language/{language}', 'LanguageController@update')->name('set-language');

    Route::put('users', 'UserController@updateMany'); // obrisati?
    Route::get('activity-log', 'AdminController@activityLog')->name('activity-log');

    Route::post('newsletter', 'NewsletterController@store')->name('store-newsletter');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected static $logAttributes = ['name', 'email'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Laracode/UserController.php
<?php

namespace App\Http\Controllers\Laracode;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax())
            return DataTables::eloquent(
                User::query()->with(['roles', 'permissions']))
                    ->addColumn('action', function($user) {
                           return view('lc-admin.users.datatables', compact('user'));
                       })
                    ->make(true);

        return view('lc-admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();
        $permissions = Permission::get();

        return view('lc-admin.users.create', compact('roles', 'permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        $roles = array_flatten(
            Role::whereIn('id', [$request->roles])
                ->get(['name'])
                ->toArray()
            );

        $permissions = array_flatten(
            Permission::whereIn('id', [$request->permissions])
                ->get(['name'])
                ->toArray()
            );

        activity()
            ->performedOn($user)
            ->causedBy(Auth::user())
            ->withProperties([
                'attributes' => [
                    'roles' => implode(', ', $roles)
                ]
            ])
            ->log('Synced roles');

        activity()
            ->performedOn($user)
            ->causedBy(Auth::user())
            ->withProperties([
                'attributes' => [
                    'permissions' => implode(', ', $permissions)
                ]
            ])
            ->log('Synced permissions');

        $user->syncRoles($request->roles);
        $user->syncPermissions($request->permissions);

        switch ($request->action) {

            case 'save':
                return redirect()->route('lc-admin.users.edit', ['user' => $user->id]);
            
            case 'save-and-new':
                return redirect()->route('lc-admin.users.create');

            case 'save-and-back':
                return redirect()->route('lc-admin.users.index');
        }
    }

    public function edit(User $user) {

        $roles = Role::get();
        $permissions = Permission::get();
        return view('admin.users.edit', compact('roles', 'permissions', 'user'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('lc-admin.users.profile');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $roles = array_flatten(
            Role::whereIn('id', [$request->roles])
                ->get(['name'])
                ->toArray()
            );

        $permissions = array_flatten(
            Permission::whereIn('id', [$request->permissions])
                ->get(['name'])
                ->toArray()
            );

        // activity()
        //     ->performedOn($user)
        //     ->causedBy(Auth::user())
        //     ->withProperties([
        //         'attributes' => '{' . implode(', ', $roles) . '}',
        //         'old' => '{' . implode(', ', $user->roles->pluck('name')->toArray()) . '}'
        //     ])
        //     ->log('Synced roles');

        // activity()
        //     ->performedOn($user)
        //     ->causedBy(Auth::user())
        //     ->withProperties([
        //         'attributes' => '{' . implode(', ', $permissions) . '}',
        //         'old' => '{' . implode(', ', $user->permissions->pluck('name')->toArray()) . '}'
        //     ])
        //     ->log('Synced permissions');

        $user->syncRoles($request->roles);
        $user->syncPermissions($request->permissions);

        $user->update([
            'name' => $request->name,
            'email' => $request->email,
        ]);
        switch ($request->action) {

            case 'save':
                return redirect()->route('lc-admin.users.edit', ['user' => $user->id]);
            
            case 'save-and-new':
                return redirect()->route('lc-admin.users.create');

            case 'save-and-back':
                return redirect()->route('lc-admin.users.index');
        }
    }

    public function updateMany(Request $request)
    {
        $users = User::findMany($request->ids);

        $users->syncRoles($request->roles);
        $users->syncPermissions($request->permissions);

        return 200;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);

        return 200;
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Create User')
@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
	<!-- BEGIN: Subheader -->
	<div class="m-subheader ">
		<div class="d-flex align-items-center">
			{{ Breadcrumbs::render('lc-admin.users.create') }}
		</div>
	</div>
	<!-- END: Subheader -->    
	<div class="m-content">
		<div class="row">
			<div class="col-lg-12">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--mobile">
					<div class="m-portlet__head">
						<div class="m-portlet__head-progress">
							<!-- here can place a progress bar-->
						</div>
						<div class="m-portlet__head-wrapper">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text">
										Create new user
									</h3>
								</div>
							</div>
							<div class="m-portlet__head-tools">
								<a href="{{ route('lc-admin.users.index') }}" class="btn btn-secondary m-btn m-btn--icon m-btn--sm m--margin-right-10">
									<span>
										<i class="la la-arrow-left"></i>
										<span>Back</span>
									</span>
								</a>
								<div class="btn-group">
									<button name="save" type="button" class="submit-form btn btn-accent m-btn m-btn--icon m-btn--sm">
										<span>
											<i class="la la-check"></i>
											<span>Save</span>
										</span>
									</button>
									<button type="button" class="btn btn-accent  dropdown-toggle dropdown-toggle-split m-btn m-btn--sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									</button>
									<div class="dropdown-menu dropdown-menu-right">
										<button name="save-and-new" type="button" class="submit-form dropdown-item submit-form btn m-btn--icon">
											<span>
												<i class="la la-check"></i>
												<span>Save & New</span>
											</span>
										</button>
										<button name="save-and-back" type="button" class="submit-form dropdown-item submit-form btn m-btn--icon">
											<span>
												<i class="la la-check"></i>
												<span>Save & Back</span>
											</span>
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="m-portlet__body">
						<form id="user-form" class="m-form m-form--label-align-left- m-form--state" action="{{ route('lc-admin.users.store') }}" method="POST">
							@csrf
							<input type="hidden" name="action">
							<!--begin: Form Body -->
							<div class="m-portlet__body">
								<div class="row">
									<div class="col-xl-8 offset-xl-2">
										<div class="m-form__section m-form__section--first">
											<div class="m-form__heading">
												<h3 class="m-form__heading-title">Account Details</h3>
											</div>
											<div class="form-group m-form__group row {{ $errors->has('name') ? 'has-danger' : null }}">
												<label class="col-xl-3 col-lg-3 col-form-label">* Name:</label>
												<div class="col-xl-9 col-lg-9">
													<input type="text" name="name" class="form-control m-input" value="{{ old('name')}}" placeholder="">
													@if ($errors->has('name'))
													<div class="form-control-feedback">
														{{ $errors->first('name') }}
													</div>
													@else
													<span class="m-form__help">Please enter your first and last names</span>
													@endif
												</div>

											</div>
											<div class="form-group m-form__group row {{ $errors->has('email') ? 'has-danger' : null }}">
												<label class="col-xl-3 col-lg-3 col-form-label">* Email:</label>
												<div class="col-xl-9 col-lg-9">
													<input type="email" name="email" class="form-control m-input" value="{{ old('email') }}" placeholder="">
													@if ($errors->has('email'))
													<div class="form-control-feedback">
														{{ $errors->first('email') }}
													</div>
													@else
													<span class="m-form__help">Please enter user email</span>
													@endif
												</div>
											</div>
											<div class="form-group m-form__group row">
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('username') ? 'has-danger' : null }}">
													<label class="form-control-label">* Username:</label>
													<input type="text" name="username" class="form-control m-input" value="{{ old('username') }}" placeholder="">
													@if ($errors->has('username'))
													<div class="form-control-feedback">
														{{ $errors->first('username') }}
													</div>
													@else
													<span class="m-form__help">Please enter unique username</span>
													@endif
												</div>
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('password') ? 'has-danger' : null }}">
													<label class="form-control-label">* Password:</label>
													<input type="password" name="password" class="form-control m-input" placeholder="">
													@if ($errors->has('password'))
													<div class="form-control-feedback">
														{{ $errors->first('password') }}
													</div>
													@else
													<span class="m-form__help">Please enter minimal 6 characters</span>
													@endif
												</div>
											</div>
										</div>
										<div class="m-separator m-separator--dashed m-separator--lg"></div>
										<div class="m-form__section">
											<div class="m-form__heading">
												<h3 class="m-form__heading-title">Client Settings</h3>
											</div>
											<div class="form-group m-form__group row">
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('roles') ? 'has-danger' : null }}">
													<label class="form-control-label">* Roles:</label>
													<div class="m-checkbox-inline">
														@foreach($roles as $role)
														<label class="m-checkbox m-checkbox--solid m-checkbox--brand">
															<input type="checkbox" name="roles[]" value="{{ $role->id }}" {{ in_array($role->id, old('roles', [])) ? 'checked' : null }}> {{ $role->name }} 
															<span></span>
														</label>
														@endforeach
													</div>
													@if ($errors->has('roles'))
													<div class="form-control-feedback">
														{{ $errors->first('roles') }}
													</div>
													@else
													<span class="m-form__help">Please select user group</span>
													@endif
												</div>
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('permissions') ? 'has-danger' : null }}">
													<label class="form-control-label">* Permissions:</label>
													<div class="m-checkbox-inline">
														@foreach($permissions as $permission)
														<label class="m-checkbox m-checkbox--solid m-checkbox--brand">
															<input type="checkbox" name="permissions[]" value="{{ $permission->id }}" {{ in_array($permission->id, old('permissions', [])) ? 'checked' : null }}> {{ $permission->name }} 
															<span></span>
														</label>
														@endforeach
													</div>
													@if ($errors->has('permissions'))
													<div class="form-control-feedback">
														{{ $errors->first('permissions') }}
													</div>
													@else
													<span class="m-form__help">Please select user permission</span>
													@endif
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				<!--end::Portlet-->
			</div>
		</div>		        
	</div>
</div>

@endsection
@section('external-js')
<script>
	$('.submit-form').click(function (e) {
		$('input[name=action]').val($(this).attr('name'))
		$('form#user-form').submit();
	})

</script>
@endsection

resources/views/admin/users/datatables.blade.php
<form action="{{ route('lc-admin.users.destroy', [$user->id]) }}" method="POST" class="float-left">
   {{method_field('DELETE')}}
   @csrf
   <button type="submit" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Drop"><i class="la la-remove"></i></button>
</form>
<a href="{{ route('lc-admin.users.edit', ['users' => $user->id]) }}" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="View"><i class="la la-edit"></i></a>

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Create User')
@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
	<!-- BEGIN: Subheader -->
	<div class="m-subheader ">
		<div class="d-flex align-items-center">
			{{ Breadcrumbs::render('lc-admin.users.create') }}
		</div>
	</div>
	<!-- END: Subheader -->    
	<div class="m-content">
		<div class="row">
			<div class="col-lg-12">
				<!--begin::Portlet-->
				<div class="m-portlet m-portlet--mobile">
					<div class="m-portlet__head">
						<div class="m-portlet__head-progress">
							<!-- here can place a progress bar-->
						</div>
						<div class="m-portlet__head-wrapper">
							<div class="m-portlet__head-caption">
								<div class="m-portlet__head-title">
									<h3 class="m-portlet__head-text">
										Create new user
									</h3>
								</div>
							</div>
							<div class="m-portlet__head-tools">
								<a href="{{ route('lc-admin.users.index') }}" class="btn btn-secondary m-btn m-btn--icon m-btn--sm m--margin-right-10">
									<span>
										<i class="la la-arrow-left"></i>
										<span>Back</span>
									</span>
								</a>
								<div class="btn-group">
									<button name="save" type="button" class="submit-form btn btn-accent m-btn m-btn--icon m-btn--sm">
										<span>
											<i class="la la-check"></i>
											<span>Save</span>
										</span>
									</button>
									<button type="button" class="btn btn-accent  dropdown-toggle dropdown-toggle-split m-btn m-btn--sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									</button>
									<div class="dropdown-menu dropdown-menu-right">
										<button name="save-and-new" type="button" class="submit-form dropdown-item submit-form btn m-btn--icon">
											<span>
												<i class="la la-check"></i>
												<span>Save & New</span>
											</span>
										</button>
										<button name="save-and-back" type="button" class="submit-form dropdown-item submit-form btn m-btn--icon">
											<span>
												<i class="la la-check"></i>
												<span>Save & Back</span>
											</span>
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="m-portlet__body">
						<form id="user-form" class="m-form m-form--label-align-left- m-form--state" action="{{ route('lc-admin.users.update', $user->id) }}" method="POST">
							{{method_field('PATCH')}}
							@csrf
							<input type="hidden" name="action">
							<!--begin: Form Body -->
							<div class="m-portlet__body">
								<div class="row">
									<div class="col-xl-8 offset-xl-2">
										<div class="m-form__section m-form__section--first">
											<div class="m-form__heading">
												<h3 class="m-form__heading-title">Account Details</h3>
											</div>
											<div class="form-group m-form__group row {{ $errors->has('name') ? 'has-danger' : null }}">
												<label class="col-xl-3 col-lg-3 col-form-label">* Name:</label>
												<div class="col-xl-9 col-lg-9">
													<input type="text" name="name" class="form-control m-input" value="{{ old('name', $user->name)}}" placeholder="">
													@if ($errors->has('name'))
													<div class="form-control-feedback">
														{{ $errors->first('name') }}
													</div>
													@else
													<span class="m-form__help">Please enter your first and last names</span>
													@endif
												</div>

											</div>
											<div class="form-group m-form__group row {{ $errors->has('email') ? 'has-danger' : null }}">
												<label class="col-xl-3 col-lg-3 col-form-label">* Email:</label>
												<div class="col-xl-9 col-lg-9">
													<input type="email" name="email" class="form-control m-input" value="{{ old('email', $user->email) }}" placeholder="">
													@if ($errors->has('email'))
													<div class="form-control-feedback">
														{{ $errors->first('email') }}
													</div>
													@else
													<span class="m-form__help">Please enter user email</span>
													@endif
												</div>
											</div>
											<div class="form-group m-form__group row">
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('username') ? 'has-danger' : null }}">
													<label class="form-control-label">* Username:</label>
													<input type="text" name="username" class="form-control m-input" value="{{ old('username', $user->username) }}" placeholder="">
													@if ($errors->has('username'))
													<div class="form-control-feedback">
														{{ $errors->first('username') }}
													</div>
													@else
													<span class="m-form__help">Please enter unique username</span>
													@endif
												</div>
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('password') ? 'has-danger' : null }}">
													<label class="form-control-label">* Password:</label>
													<input type="password" name="password" class="form-control m-input" placeholder="">
													@if ($errors->has('password'))
													<div class="form-control-feedback">
														{{ $errors->first('password') }}
													</div>
													@else
													<span class="m-form__help">Please enter minimal 6 characters</span>
													@endif
												</div>
											</div>
										</div>
										<div class="m-separator m-separator--dashed m-separator--lg"></div>
										<div class="m-form__section">
											<div class="m-form__heading">
												<h3 class="m-form__heading-title">Client Settings</h3>
											</div>
											<div class="form-group m-form__group row">
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('roles') ? 'has-danger' : null }}">
													<label class="form-control-label">* Roles:</label>
													<div class="m-checkbox-inline">
														@foreach($roles as $role)
														<label class="m-checkbox m-checkbox--solid m-checkbox--brand">
															<input type="checkbox" name="roles[]" value="{{ $role->id }}" {{ in_array($role->id, old('roles', (array)$user->roles)) ? 'checked' : null }}> {{ $role->name }} 
															<span></span>
														</label>
														@endforeach
													</div>
													@if ($errors->has('roles'))
													<div class="form-control-feedback">
														{{ $errors->first('roles') }}
													</div>
													@else
													<span class="m-form__help">Please select user group</span>
													@endif
												</div>
												<div class="col-lg-6 m-form__group-sub {{ $errors->has('permissions') ? 'has-danger' : null }}">
													<label class="form-control-label">* Permissions:</label>
													<div class="m-checkbox-inline">
														@foreach($permissions as $permission)
														<label class="m-checkbox m-checkbox--solid m-checkbox--brand">
															<input type="checkbox" name="permissions[]" value="{{ $permission->id }}" {{ in_array($permission->id, old('permissions', (array)$user->permissions)) ? 'checked' : null }}> {{ $permission->name }} 
															<span></span>
														</label>
														@endforeach
													</div>
													@if ($errors->has('permissions'))
													<div class="form-control-feedback">
														{{ $errors->first('permissions') }}
													</div>
													@else
													<span class="m-form__help">Please select user permission</span>
													@endif
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				<!--end::Portlet-->
			</div>
		</div>		        
	</div>
</div>

@endsection
@section('external-js')
<script>
	$('.submit-form').click(function (e) {
		$('input[name=action]').val($(this).attr('name'))
		$('form#user-form').submit();
	})

</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')
@section('title', 'Users')
@section('external-css')
 <!--begin::Page Vendors Styles -->
<link href="{{ asset('METRONIC/assets/vendors/custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css" /><!--RTL version:<link href="../../../assets/vendors/custom/datatables/datatables.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
@endsection
@section('content')
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            {{ Breadcrumbs::render('lc-admin.users') }}
        </div>
    </div>
<!-- END: Subheader -->             
<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-progress">
                <!-- here can place a progress bar-->
            </div>
            <div class="m-portlet__head-wrapper">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{ __('Users') }}
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <a href="{{ route('lc-admin.users.create') }}" class="btn btn-accent m-btn m-btn--icon m-btn--sm m--margin-right-10">
                        <span>
                            <i class="la la-plus"></i>
                            <span>{{ __('New user') }}</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                <thead>
                    <tr>
                        <th>{{ __('Name') }}</th>
                        <th>{{ __('Email') }}</th>
                        <th>{{ __('Roles') }}</th>
                        <th>{{ __('Special Permissions') }}</th>
                        <th>{{ __('Action') }}</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- END EXAMPLE TABLE PORTLET-->             
</div>

@endsection
@section('external-js')

<script src="{{ asset('js/datatables.bundle.js') }}"></script>
<script src="{{ asset('admin/users-datatable.js') }}"></script>

@endsection