routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index');

Route::get('lc-admin', 'Laracode\AdminController@index')->name('lc-admin');
Route::group(['as' => 'lc-admin.', 'prefix' => 'lc-admin', 'middleware' => ['auth', 'permission:admin panel'], 'namespace' => 'Laracode'], function () {

    Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    // Route::resource('roles', 'RoleController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('roles', 'RoleController', ['except' => ['show', 'edit']]);
    // Route::resource('permissions', 'PermissionController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('permissions', 'PermissionController', ['except' => ['show', 'edit']]);
    Route::resource('users', 'UserController');

    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::post('languages/{name}', 'LanguageController@store')->name('store-language');
    Route::get('set-language/{language}', 'LanguageController@update')->name('set-language');

    Route::put('users', 'UserController@updateMany'); // obrisati?
    Route::get('activity-log', 'AdminController@activityLog')->name('activity-log');

    Route::post('newsletter', 'NewsletterController@store')->name('store-newsletter');
});

resources/views/lc-admin/layouts/breadcrumbs.blade.php
<nav class="breadcrumb ks-default">
	@foreach ($breadcrumbs as $breadcrumb)	
	@if($breadcrumb->url && $breadcrumb->title == 'Home')
    <a class="breadcrumb-item ks-breadcrumb-icon" href="{{ $breadcrumb->url }}">
        <span class="la la-home ks-icon"></span>
    </a>
    @elseif($breadcrumb->url)
    <a href="{{ $breadcrumb->url }}" class="breadcrumb-item">{{ $breadcrumb->title }}</a>
    @elseif($breadcrumb->url && $loop->last)
    <span class="breadcrumb-item active" href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</span>
    @endif
    @endforeach
</nav>

resources/views/lc-admin/layouts/header.blade.php
    <!-- BEGIN HEADER -->
<nav class="navbar ks-navbar">
    <!-- BEGIN HEADER INNER -->
    <!-- BEGIN LOGO -->
    <div href="index.html" class="navbar-brand">
        <!-- BEGIN RESPONSIVE SIDEBAR TOGGLER -->
        <a href="#" class="ks-sidebar-toggle"><i class="ks-icon la la-bars" aria-hidden="true"></i></a>
        <a href="#" class="ks-sidebar-mobile-toggle"><i class="ks-icon la la-bars" aria-hidden="true"></i></a>
        <!-- END RESPONSIVE SIDEBAR TOGGLER -->

        <div class="ks-navbar-logo">
            <a href="{{ route('lc-admin')}} " class="ks-logo">LC ADMIN</a>
        </div>
    </div>
    <!-- END LOGO -->

    <!-- BEGIN MENUS -->
    <div class="ks-wrapper">
        <nav class="nav navbar-nav">
            <!-- BEGIN NAVBAR MENU -->
            <div class="ks-navbar-menu">
                <a class="nav-item nav-link" href="#">BRZI LINK</a>
                <a class="nav-item nav-link" href="#">BRZI LINK</a>
                <a class="nav-item nav-link" href="#">BRZI LINK</a>
            </div>
            <!-- END NAVBAR MENU -->

            <!-- BEGIN NAVBAR ACTIONS -->
            <div class="ks-navbar-actions">
                <!-- BEGIN NAVBAR ACTION BUTTON -->
                <!--
                <div class="nav-item nav-link btn-action-block">
                    <a class="btn btn-danger" href="#">
                        <span class="ks-action">Activate Your Account</span>
                        <span class="ks-description">trial ends in 1 day</span>
                    </a>
                </div>
            -->
                <!-- END NAVBAR ACTION BUTTON -->

                <!-- BEGIN NAVBAR LANGUAGES -->
                <div class="nav-item dropdown ks-languages">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        {{ strtoupper(\App::getLocale()) }} <span class="ks-text">Languages</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right ks-scrollable" aria-labelledby="Preview">
                        <div class="ks-wrapper">
                            @foreach(config('app.admin_locales') as $language)
                            <a href="{{ route('lc-admin.set-language', $language) }}" class="ks-language ks-selected">
                                {{-- <span class="flag-icon flag-icon-{{$language}} ks-icon"></span> --}}
                                <img class="flag-icon" src="{{ asset('theme/lc-admin/custom/flags/' . $language . '.png') }}" alt="">
                                <span class="ks-text">{{ ucfirst(__($language)) }}</span>
                            </a>
                            @endforeach
                        </div>
                    </div>
                </div>
                <!-- END NAVBAR LANGUAGES -->

                <!-- BEGIN NAVBAR USER -->
                <div class="nav-item dropdown ks-user">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="ks-avatar">
                            <img src="{{ asset('theme/lc-admin/assets/img/avatars/avatar-13.jpg') }}" width="36" height="36">
                        </span>
                        <span class="ks-info">
                            <span class="ks-name">{{ Auth::user()->name }}</span>
                            <span class="ks-description">Premium User</span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Preview">
                        <a class="dropdown-item" href="#">
                            <span class="la la-user ks-icon"></span>
                            <span>{{ __('My Profile') }}</span>
                        </a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <span class="la la-sign-out ks-icon" aria-hidden="true"></span>
                            <span>{{__('Logout')}}</span>
                            <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;"> @csrf </form>
                        </a>
                    </div>
                </div>
                <!-- END NAVBAR USER -->
            </div>
            <!-- END NAVBAR ACTIONS -->
        </nav>

        <!-- BEGIN NAVBAR ACTIONS TOGGLER -->
        <nav class="nav navbar-nav ks-navbar-actions-toggle">
            <a class="nav-item nav-link" href="#">
                <span class="la la-ellipsis-h ks-icon ks-open"></span>
                <span class="la la-close ks-icon ks-close"></span>
            </a>
        </nav>
        <!-- END NAVBAR ACTIONS TOGGLER -->

        <!-- BEGIN NAVBAR MENU TOGGLER -->
        <nav class="nav navbar-nav ks-navbar-menu-toggle">
            <a class="nav-item nav-link" href="#">
                <span class="la la-th ks-icon ks-open"></span>
                <span class="la la-close ks-icon ks-close"></span>
            </a>
        </nav>
        <!-- END NAVBAR MENU TOGGLER -->
    </div>
    <!-- END MENUS -->
    <!-- END HEADER INNER -->
</nav>
<!-- END HEADER -->

resources/views/lc-admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8">
    <title>@yield ('title', 'Administration') | Laracode Panel</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @yield('external-meta')
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/fonts/line-awesome/css/line-awesome.min.css') }}">
    <!--<link rel="stylesheet" type="text/css" href="assets/fonts/open-sans/styles.css">-->

    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/fonts/montserrat/styles.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/tether/css/tether.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.jscrollpane.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/libs/flag-icon-css/css/flag-icon.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/common.min.css') }}">
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/themes/primary.min.css') }}">
    <link class="ks-sidebar-dark-style" rel="stylesheet" type="text/css" href="{{ asset('theme/lc-admin/assets/styles/themes/sidebar-black.min.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/lc-admin/libs/notify/bootstrap-notify.min.css') }}">
    <!-- END THEME STYLES -->
    @yield('external-css')
</head>
<!-- END HEAD -->

<body class="ks-navbar-fixed ks-sidebar-default ks-sidebar-position-fixed ks-page-header-fixed ks-theme-primary ks-page-loading"> <!-- remove ks-page-header-fixed to unfix header -->

@include('lc-admin.layouts.header')






<div class="ks-page-container">
    
@include('lc-admin.layouts.sidebar')

@yield('content')
</div>

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ asset('theme/lc-admin/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/popper/popper.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/responsejs/response.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/loading-overlay/loadingoverlay.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/tether/js/tether.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.jscrollpane.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/jscrollpane/jquery.mousewheel.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/flexibility/flexibility.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/notify/bootstrap-notify.min.js') }}"></script>
<script src="{{ asset('theme/lc-admin/libs/velocity/velocity.min.js') }}"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="{{ asset('theme/lc-admin/assets/scripts/common.min.js') }}"></script>
<!-- END THEME LAYOUT SCRIPTS -->

@include ('admin.layouts.notifications')

@yield('external-js')

<div class="ks-mobile-overlay"></div>

<!-- BEGIN SETTINGS BLOCK -->
<div class="ks-settings-slide-block">
    <a class="ks-settings-slide-control">
        <span class="ks-icon la la-cog"></span>
    </a>

    <div class="ks-header">
        <span class="ks-text">Layout Options</span>
        <a class="ks-settings-slide-close-control">
            <span class="ks-icon la la-close"></span>
        </a>
    </div>

    <ul class="ks-settings-list">
        <li>
            <span class="ks-text">Collapsed Sidebar</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-sidebar-checkbox-toggle">
                <input type="checkbox" value="1">
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">Fixed page header</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-page-header-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">Dark/Light Sidebar</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-sidebar-style-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
        <li>
            <span class="ks-text">White/Gray Content Background</span>
            <label class="ks-checkbox-slider ks-on-off ks-primary ks-content-bg-checkbox-toggle">
                <input type="checkbox" value="0" checked>
                <span class="ks-indicator"></span>
                <span class="ks-on">On</span>
                <span class="ks-off">Off</span>
            </label>
        </li>
    </ul>
</div>
<!-- END SETTINGS BLOCK -->
</body>
</html>

resources/views/lc-admin/layouts/sidebar.blade.php
    <!-- BEGIN DEFAULT SIDEBAR -->
<div class="ks-column ks-sidebar ks-info">
    <div class="ks-wrapper ks-sidebar-wrapper">
        <ul class="nav nav-pills nav-stacked">

            <li class="nav-item">
                <a class="nav-link"  href="{{ route('lc-admin.dashboard') }}" >
                    <span class="ks-icon la la-dashboard"></span>
                    <span>{{ __('Dashboard') }}</span>
                </a>
            </li>
            <li class="nav-item dropdown {{ strpos(Route::currentRouteName(), 'lc-admin.users') === 0 || strpos(Route::currentRouteName(), 'lc-admin.roles') === 0 || strpos(Route::currentRouteName(), 'lc-admin.permissions') === 0 ? 'open' : '' }}">
                <a class="nav-link dropdown-toggle"  href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="ks-icon la la-users"></span>
                    <span>{{ __('Users') }}</span>
                </a>
                <div class="dropdown-menu ">
                    <a href="{{ route('lc-admin.users.index') }}" class="dropdown-item">{{ __('Users') }}</a>
                    <a href="{{ route('lc-admin.roles.index') }}" class="dropdown-item">{{ __('Roles') }}</a>
                    <a href="{{ route('lc-admin.permissions.index') }}" class="dropdown-item">{{ __('Premissions') }}</a>
                </div>
            </li>
            
        
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"  href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="ks-icon la la-sliders"></span>
                    <span>{{ __('Tools & Settings') }}</span>
                </a>
                <div class="dropdown-menu">
                    <a href="{{ route('lc-admin.languages') }}" class="dropdown-item">{{ __('Languages')}}</a>
                    <a href="{{ route('lc-admin.activity-log') }}" class="dropdown-item">{{ __('Activity log') }}</a>
                </div>
            </li>
        </ul>
        <div class="ks-sidebar-extras-block">
            <div class="ks-sidebar-copyright">2018 &copy; Admin panel  by <a href="https://laracode.net" class="m-link">Laracode.net</a></div>
        </div>
    </div>
</div>
<!-- END DEFAULT SIDEBAR -->